### ISSUE TITLE
Shift schedule: "Simple schedule" throws error.

### ISSUE THREAD

**Issue by adamjrice** [BurningFlipside/VolunteerSystem#81]
Error text as follows:

````
Exception: Unable to locate object with ID in /var/www/secure/fvs/app/class.VolunteerObject.php:20 Stack trace: #0 /var/www/secure/fvs/app/class.VolunteerProfile.php(24): VolunteerObject->__construct('', NULL, 'participants', 'uid') #1 /var/www/secure/fvs/app/class.VolunteerShift.php(93): VolunteerProfile->__construct('') #2 /var/www/secure/fvs/app/Schedules/class.SimplePDF.php(73): VolunteerShift->__get('participantObj') #3 /var/www/secure/fvs/app/Schedules/class.SimplePDF.php(26): Schedules\SimplePDF->createPDFBody() #4 /var/www/secure/fvs/api/v1/class.DepartmentAPI.php(209): Schedules\SimplePDF->__construct(Array, Array) #5 /var/www/secure/fvs/api/v1/class.DepartmentAPI.php(198): DepartmentAPI->generateSimplePDFSchedule(Array, Array, Object(Slim\Http\Response)) #6 [internal function]: DepartmentAPI->generateShiftSchedule(Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #7 /var/www/common/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #8 /var/www/common/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array) #9 /var/www/common/Http/Rest/class.SerializationMiddleware.php(80): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #10 [internal function]: Http\Rest\SerializationMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route)) #11 /var/www/common/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Http\Rest\SerializationMiddleware), Array) #12 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route)) #13 /var/www/common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route)) #14 /var/www/common/Http/Rest/class.CORSMiddleware.php(46): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #15 [internal function]: Http\Rest\CORSMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #16 /var/www/common/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Http\Rest\CORSMiddleware), Array) #17 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #18 /var/www/common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #19 /var/www/common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #20 /var/www/common/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #21 /var/www/common/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response)) #22 /var/www/common/Http/class.AuthMiddleware.php(91): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response)) #23 [internal function]: Http\AuthMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Http\WebSite)) #24 /var/www/common/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Http\AuthMiddleware), Array) #25 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Http\WebSite)) #26 /var/www/common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Http\WebSite)) #27 /var/www/common/Http/class.ODataMiddleware.php(16): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #28 [internal function]: Http\ODataMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #29 /var/www/common/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Http\ODataMiddleware), Array) #30 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #31 /var/www/common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Closure)) #32 /var/www/common/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response)) #33 /var/www/common/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response)) #34 /var/www/common/vendor/slim/slim/Slim/App.php(313): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #35 /var/www/secure/fvs/api/v1/index.php(45): Slim\App->run() #36 {main}
````

**Comment by pboyd04** [comment]
Fixed if you want to verify?

**Comment by adamjrice** [comment]
Quoted nicknames are triple-quoted, eg Jason "'""The JayBird""'" Spees. Not sure if this is happening at a deeper level or when rendering the HTML. Otherwise seems correct

**Comment by pboyd04** [comment]
He added all those quotes for some reason. Just one set of quotes is added by the system.

**Comment by pboyd04** [comment]
https://secure.burningflipside.com/fvs/_admin/volunteers.php
